apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-ovn
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-ovn-v2
      version: 1.14.2
      sourceRef:
        kind: HelmRepository
        name: kube-ovn
        namespace: flux-system
  values:
    images:
      kubeovn:
        tag: v1.14.5

    masterNodes:
      - 10.2.1.126
    masterNodesLabels:
      node-role.kubernetes.io/control-plane: ""

    networking:
      stack: "IPv4"

    ovsOvn:
      disableModulesManagement: true
      ovsDirectory: "/var/lib/openvswitch"
      ovnDirectory: "/var/lib/ovn"
    cni:
      mountToolingDirectory: false
